# .github/labeler.yml
bug:
  - "**bug**"
  - "**fix**"
  - "**error**"
  - "**issue**"

enhancement:
  - "**feature**"
  - "**enhancement**"
  - "**add**"
  - "**improve**"

documentation:
  - "**docs**"
  - "**documentation**"
  - "**readme**"
