# .github/workflows/labeler.yml
name: "Labeler"

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml
